config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :blog_posts
  resources :users
  resources :tags
  root 'blog_posts#index'
  get  '/index',    to: 'static_pages#index'
  get  '/post',    to: 'static_pages#post'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get   '/blog_posts/user/index', to: 'blog_posts#blogpost_user_index'

end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  belongs_to :user
  has_many :taggings
  has_many :tags, through: :taggings

  validates :title,  presence: true, length: { maximum: 50}
  validates :summary,  presence: true, length: { maximum: 150}
  validates :content,  presence: true
  validates :title_image_url,  presence: true, length: { maximum: 255}
  validates :user_id, presence: true

  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end  

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end  
  
  
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  include SessionsHelper
  before_action :set_blog_post, only: %i[ show edit update destroy ]
  before_action :logged_in_user, only: [:new, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /blog_posts or /blog_posts.json
  def index
    if params[:search].present?
      search_term = "%#{params[:search].downcase}%"
      @blog_posts = BlogPost.where("LOWER(title) LIKE ? OR LOWER(summary) LIKE ?", search_term, search_term).order(created_at: :desc)
    else
      @blog_posts = BlogPost.order(created_at: :desc)
    end
  end  

  def blogpost_user_index
    @blog_posts = current_user.blog_posts.order(created_at: :desc)
  end

  # GET /blog_posts/1 or /blog_posts/1.json
  def show
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
    @user = User.find(current_user.id)
    @blogpost = BlogPost.find(params[:id])
    
    if !@user.is_admin && @blogpost.user_id != @user.id 
      redirect_to(root_url) 
    end   
  end

  # POST /blog_posts or /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to blog_post_url(@blog_post), notice: "Blog post was successfully created." }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1 or /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to blog_post_url(@blog_post), notice: "Blog post was successfully updated." }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1 or /blog_posts/1.json
  def destroy
    @blog_post.taggings.destroy_all
    @blog_post.destroy

    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: "Blog post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :summary, :content, :user_id, :title_image_url, :search, :tag_list)
    end

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(current_user.id)
      redirect_to(root_url) unless @user == current_user || current_user.is_admin? 
    end
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with(model: blog_post) do |form| %>
  <% if blog_post.errors.any? %>
    <div id="error_explanation_new">
      <h6><%= pluralize(blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h6>
      <ul>
        <% blog_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-floating">
  <%= form.text_field :title, class: "form-control", id: "title", placeholder: "Enter title...", "data-sb-validations" => "required" %>
  <%= form.label :title, "Title", class: "form-label", for: "title" %>
  <div class="invalid-feedback" data-sb-feedback="title:required">A title is required.</div>
</div>
<div class="form-floating">
  <%= form.text_field :summary, class: "form-control", id: "summary", placeholder: "Enter summary...", "data-sb-validations" => "required" %>
  <%= form.label :summary, "Summary", class: "form-label", for: "summary" %>
  <div class="invalid-feedback" data-sb-feedback="summary:required">A summary is required.</div>
</div>
<div class="form-floating">
  <%= form.text_area :content, class: "form-control", id: "content", placeholder: "Enter content...", "data-sb-validations" => "required" %>
  <%= form.label :content, "Content", class: "form-label", for: "content" %>
  <div class="invalid-feedback" data-sb-feedback="content:required">Content is required.</div>
</div>
  <% if current_user.is_admin%>
    <div class="form-floating">
      <%= form.hidden_field :user_id, value: @blog_post.user_id %>
    </div>
  <% else %>
    <div class="form-floating">
      <%= form.hidden_field :user_id, value: current_user.id %>
    </div>
  <% end %>
<div class="form-floating">
  <%= form.text_field :title_image_url, class: "form-control", id: "title_image_url", placeholder: "Enter title image URL...", "data-sb-validations" => "required" %>
  <%= form.label :title_image_url, "Title Image URL", class: "form-label", for: "title_image_url" %>
  <div class="invalid-feedback" data-sb-feedback="title_image_url:required">Title Image URL is required.</div>
</div>
<div class="form-floating">
  <%= form.text_field :tag_list, class: "form-control", id: "tag_list", placeholder: "Enter tags...", "data-sb-validations" => "required" %>
  <%= form.label :tag_list, "Tag List", class: "form-label", for: "tag_list" %>
  <div class="invalid-feedback" data-sb-feedback="tag_list:required">Tag List is required.</div>
</div>

<br>
<button class="btn btn-primary text-uppercase" id="submitButton" type="submit">Send</button>
<% end %>

app/views/blog_posts/blogpost_user_index.html.erb
<% provide(:title, 'Home') %>
<% provide(:heading, 'My Blog') %>
<% provide(:sub_heading, 'You can see all of your blog posts here') %>
<% provide(:bg_image, 'home-bg.jpg') %>

<!-- Main Content--> 
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <% if logged_in? %>
                    <button class ="btn btn-light"><%= link_to 'New Blog Post', new_blog_post_path %></button>
                <% end %>
              <% @blog_posts.each do |blog_post| %>
                <!-- Post preview-->
                <div class="post-preview">
                    <%= link_to blog_post do %>
                        <h2 class="post-title"><%= blog_post.title %></h2>
                        <h3 class="post-subtitle"><%= blog_post.summary %></h3>
                        <% if logged_in? %>
                            <%= link_to 'Edit', edit_blog_post_path(blog_post) %> 
                            <%= link_to 'Delete', blog_post, method: :delete, data: { confirm: 'Are you sure?' }  %>
                        <% end %>
                    <% end %>
                </div>
                <!-- Divider-->
                <hr class="my-4" />
              <% end %>
              <!-- Pager-->
              <%# <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div> %>
            </div>
        </div>
    </div>
</main>

app/views/blog_posts/edit.html.erb
<% provide(:title, 'Edit Blog Post') %>
<% provide(:heading, 'Edit Blog Post') %>
<% provide(:sub_heading, 'You can edit blog post\'s information here') %>
<% provide(:bg_image, @blog_post.title_image_url) %>

<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <%= render 'form', blog_post: @blog_post %>
                <%= link_to 'Changed your mind? Go back', @blog_post %> 
            </div>
        </div>
    </div>
</main>

app/views/blog_posts/index.html.erb
<% provide(:title, 'Home') %>
<% provide(:heading, 'Blog Home') %>
<% provide(:sub_heading, 'You can see blog posts here') %>
<% provide(:bg_image, 'home-bg.jpg') %>

<!-- Main Content--> 
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <%= form_tag(blog_posts_path, method: :get, class: "mb-4") do %>
                    <div class="input-group">
                        <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search for blog posts" %>
                        <button type="submit" class="btn btn-outline-secondary">Search</button>
                    </div>
                <% end %>
                <% if logged_in? && current_user.is_admin%>
                    <button class ="btn btn-light"><%= link_to 'New Blog Post', new_blog_post_path %></button>
                <% end %>
                <% @blog_posts.each do |blog_post| %>
                    <!-- Post preview-->
                    <div class="post-preview">
                        <%= link_to blog_post do %>
                            <h2 class="post-title"><%= blog_post.title %></h2>
                            <h3 class="post-subtitle"><%= blog_post.summary %></h3>
                            <% if logged_in? && current_user.is_admin %>
                                <%= link_to 'Edit', edit_blog_post_path(blog_post) %> 
                                <%= link_to 'Delete', blog_post, method: :delete, data: { confirm: 'Are you sure?' } %>
                            <% end %>
                        <% end %>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                <% end %>
                <!-- Pager-->
                <%# <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div> %>
            </div>
        </div>
    </div>
</main>

app/views/blog_posts/new.html.erb
<% provide(:title, 'New Blog Post') %>
<% provide(:heading, 'New Blog Post') %>
<% provide(:sub_heading, 'You can create new blog post here') %>
<% provide(:bg_image, 'blog-post-bg.png') %>

<!-- Main Content--> 
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7"> 
                <%= render 'form', blog_post: @blog_post %>
                <%= link_to 'Home', blog_posts_path %>
            </div>
        </div>
    </div>
</main>

app/views/blog_posts/old_index.html.erb
<% provide(:title, 'Blog Posts') %>
<% provide(:heading, 'Blog Posts') %>
<% provide(:sub_heading, 'You can see blog post\'s information here') %>
<% provide(:bg_image, 'blog-post-bg.png') %>

<!-- Main Content--> 
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th>Title</th>
                    <th>Summary</th>
                    <th>Content</th>
                    <th>User</th>
                    <th>Title image url</th>
                    <th colspan="3"></th>
                  </tr>
                </thead>
                <tbody>
                  <% @blog_posts.each do |blog_post| %>
                    <tr>
                      <td><%= blog_post.title %></td>
                      <td><%= blog_post.summary %></td>
                      <td><%= blog_post.content %></td>
                      <td><%= blog_post.user_id %></td>
                      <td><%= blog_post.title_image_url %></td>
                      <td><%= link_to 'Show', blog_post %></td>
                      <td><%= link_to 'Edit', edit_blog_post_path(blog_post) %></td>
                      <td><%= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
              <br>
              <%= link_to 'New Blog Post', new_blog_post_path %>
            </div>
        </div>
    </div>
</main>

app/views/blog_posts/old_show.html.erb
<% provide(:title, 'Blog Posts') %>
<% provide(:heading, 'Blog Posts') %>
<% provide(:sub_heading, 'You can see blog post\'s information details here') %>
<% provide(:bg_image, 'blog-post-bg.png') %>

<!-- Main Content--> 
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
              <ul class="list-group list-group-horizontal-xxl">
                <li class="list-group-item" style="width:30%"><strong>Title</strong></li>
                <li class="list-group-item" style="width:70%"><%= @blog_post.title %></li>
              </ul>
              <ul class="list-group list-group-horizontal-xxl">
                <li class="list-group-item" style="width:30%"><strong>Summary</strong></li>
                <li class="list-group-item" style="width:70%"><%= @blog_post.summary %></li>
              </ul>
              <ul class="list-group list-group-horizontal-xxl">
                <li class="list-group-item" style="width:30%"><strong>Content</strong></li>
                <li class="list-group-item" style="width:70%"><%= @blog_post.content %></li>
              </ul>
              <ul class="list-group list-group-horizontal-xxl">
                <li class="list-group-item" style="width:30%"><strong>User</strong></li>
                <li class="list-group-item" style="width:70%"><%= @blog_post.user_id %></li>
              </ul>
              <ul class="list-group list-group-horizontal-xxl">
                <li class="list-group-item" style="width:30%"><strong>Title image url</strong></li>
                <li class="list-group-item" style="width:70%"><%= @blog_post.title_image_url %></li>
              </ul>
              <br>
                <%= link_to 'Edit', edit_blog_post_path(@blog_post) %> |
                <%= link_to 'Back', blog_posts_path %>
            </div>
            <br>
        </div>
    </div>
</main>

app/views/blog_posts/show.html.erb
<% provide(:title, 'Blog Posts') %>
<% provide(:heading, @blog_post.title) %>
<% provide(:sub_heading, @blog_post.summary) %>
<% provide(:bg_image, @blog_post.title_image_url) %>

<!-- Post Content-->
<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p style="text-align:justify"><%= @blog_post.content %></p>
                <h6>
                    Tags:
                    <% @blog_post.tags.each do |tag| %>
                        <%= link_to tag.name, tag_path(tag) %>
                    <% end %>
                </h6>

                <% if logged_in? && current_user.is_admin%>
                    <%= link_to 'All Posts', blog_posts_path %> |
                    <%= link_to 'Want to edit the post? Click here', edit_blog_post_path(@blog_post) %> 
                <% end %> 
            </div>
        </div>
    </div>
</article>