config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :blog_posts
  resources :users
  resources :tags
  root 'blog_posts#index'
  get  '/index',    to: 'static_pages#index'
  get  '/post',    to: 'static_pages#post'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get   '/blog_posts/user/index', to: 'blog_posts#blogpost_user_index'

end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings
    has_many :blog_posts, through: :taggings

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def show
        @tag = Tag.find(params[:id])
    end
      
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/show.html.erb
<!-- Post Content-->
<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <h2>Blog posts that is tagged with <%= @tag.name %></h2>
                  <br>

                  <h6>
                    <% @tag.blog_posts.each do |blog_post| %>
                      <li><%= link_to blog_post.title, blog_post_path(blog_post) %></li>
                    <% end %>
                    <br>
                  </h6>
                    <%= link_to 'Home', blog_posts_path %>

                  <% provide(:title, 'Blog Posts') %>
                  <% provide(:heading, 'Taggings') %>
                  <% provide(:sub_heading, 'You can see all of the posts that tagged with ' + @tag.name + ' tag') %>
            </div>
        </div>
    </div>
</article>