config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :blog_posts
  resources :users
  resources :tags
  root 'blog_posts#index'
  get  '/index',    to: 'static_pages#index'
  get  '/post',    to: 'static_pages#post'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get   '/blog_posts/user/index', to: 'blog_posts#blogpost_user_index'

end

app/views/layouts/_footer.html.erb
<!-- Footer-->
<footer class="border-top">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#!">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="masthead" style="background-image: url('<%= full_bg_image(yield(:bg_image)) %>')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="page-heading">
                    <h1><%= full_heading(yield(:heading)) %></h1>
                    <span class="subheading"><%= full_sub_heading(yield(:sub_heading)) %></span>
                </div>
            </div>
        </div>
    </div>
</header>

app/views/layouts/_navigation.html.erb
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
    <div class="container px-4 px-lg-5">
        <%= link_to "Blog Posts", blog_posts_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto py-4 py-lg-0">
                <li class="nav-item"><%= link_to "Home", blog_posts_path, class: "nav-link px-lg-3 py-3 py-lg-4" %></li>
                <li class="nav-item"><%= link_to "About", about_path, class: "nav-link px-lg-3 py-3 py-lg-4" %></li>
                <li class="nav-item"><%= link_to "Contact", contact_path, class: "nav-link px-lg-3 py-3 py-lg-4" %></li>
                <% if logged_in? && current_user.is_admin%>
                    <li class="nav-item"><%= link_to "Users", users_path, class: "nav-link px-lg-3 py-3 py-lg-4" %></li>
                <% end %>
                <% if logged_in? %>
                    <li class="nav-item"><%= link_to "My Blog", blog_posts_user_index_path, class: "nav-link px-lg-3 py-3 py-lg-4" %></li>
                    <li class="nav-item dropdown av-link px-lg-3 py-3 py-lg-3">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Account
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><%= link_to "Profile", current_user, class: "dropdown-item" %></li>
                            <li><%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item" %></li>
                            <li><hr class="dropdown-divider"></li>
                            <li>
                                <%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item" %>
                            </li>
                        </ul>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Log in", login_path, class: "nav-link px-lg-3 py-3 py-lg-4" %>
                    </li>
                <% end %>
            </ul>
        </div>

    </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      <meta name="description" content="" />
      <meta name="author" content="" />
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag 'application', media: 'all',
                                            'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      <%= render 'layouts/shim' %>
      <title><%= full_title(yield(:title)) %></title>
      <%# <link rel="icon" type="image/x-icon" href="/assets/favicon.ico" /> %>
      <!-- Font Awesome icons (free version)-->
      <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
      <!-- Google fonts-->
      <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
      <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
      <!-- Core theme CSS (includes Bootstrap)-->
      <%# <link href="app/assets/stylesheets/application.css" rel="stylesheet" /> %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/header' %>
    <div class="container">
      <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
            <% flash.each do |message_type, message| %>
              <div class="alert alert-<%= message_type %>"><%= message %></div>
            <% end %>
          </div>
        </div>
      <div>
    <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
    <!-- Bootstrap core JS-->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>
    